GNPy: enable setting power targets as determined from GNPy
When the GNPy support was being implemented, the code would originally
go ahead and set the desired power levels prior to intents being
installed. That does not work with our HW because we cannot set a power
target for a MC which has not been provisioned yet. So the code was
fixed to wait with power settings until the optical intent has been
installed to all devices along the path. However, there was a bug that
the actual event listener was never activated, and the per-MC power
target therefore did not happen at all.

Register our intent watcher and make sure we handle these events and
propagate power targets.

Actual power propagation can take an unspecified amount of time (it's a
NETCONF operation over SSH over network), and indeed, the default "event
sink" was not particularly happy with it:

 2020-02-23T16:33:05,162 | WARN  | onos-shared-timer | CoreEventDispatcher              | 190 - org.onosproject.onos-core-net - 2.3.1.SNAPSHOT | Event sink org.onosproject.event.ListenerRegistry exceeded execution time limit: 2168 ms; spawning new dispatch loop
 2020-02-23T16:33:05,164 | ERROR | onos-shared-timer | ListenerRegistry                 | 186 - org.onosproject.onos-api - 2.3.1.SNAPSHOT | Listener org.onosproject.odtn.impl.GnpyManager$InternalIntentListener exceeded execution time limit: 2171 ms; ejected
 2020-02-23T16:33:05,166 | INFO  | onos-shared-timer | CoreEventDispatcher              | 190 - org.onosproject.onos-core-net - 2.3.1.SNAPSHOT | Stopping watchdog task for dispatcher programming
 2020-02-23T16:33:05,167 | INFO  | onos-shared-timer | CoreEventDispatcher              | 190 - org.onosproject.onos-core-net - 2.3.1.SNAPSHOT | Starting watchdog task for dispatcher programming
 2020-02-23T16:33:05,172 | WARN  | onos-event-dispatch-programming0 | ListenerRegistry                 | 186 - org.onosproject.onos-api - 2.3.1.SNAPSHOT | Exception encountered while processing event IntentEvent{time=2020-02-23T16:33:02.993Z, type=INSTALLED, subject=OpticalConnectivityIntent{id=0x0, key=0x0, appId=DefaultApplicationId{id=92, name=org.onosproject.odtn-service}, priority=100, resources=[], src=netconf:10.0.254.105:830/10101, dst=netconf:10.0.254.103:830/10101, signalType=ODUC2, isBidirectional=true, ochSignal=Optional[OchSignal{-29 x 50.00GHz +/- 25.00GHz}], suggestedPath=Optional[DefaultPath{src=netconf:10.0.254.103:830/10101, dst=netconf:10.0.254.105:830/10101, type=INDIRECT, state=ACTIVE, expected=false, links=[DefaultLink{src=netconf:10.0.254.103:830/10101, dst=netconf:10.0.254.246:830/7, type=OPTICAL, state=ACTIVE, expected=true}, DefaultLink{src=netconf:10.0.254.246:830/100, dst=netconf:10.0.254.227:830/7, type=OPTICAL, state=ACTIVE, expected=true}, DefaultLink{src=netconf:10.0.254.227:830/100, dst=netconf:10.0.254.236:830/100, type=OPTICAL, state=ACTIVE, expected=true}, DefaultLink{src=netconf:10.0.254.236:830/7, dst=netconf:10.0.254.105:830/10101, type=OPTICAL, state=ACTIVE, expected=true}], cost=ScalarWeight{value=1.0}}], resourceGroup=null}}
 java.lang.IllegalStateException: org.onosproject.netconf.NetconfException: Failed to edit configuration.
         at org.onosproject.drivers.czechlight.CzechLightPowerConfig.doEditConfig(CzechLightPowerConfig.java:278) ~[?:?]
         at org.onosproject.drivers.czechlight.CzechLightPowerConfig.setTargetPower(CzechLightPowerConfig.java:92) ~[?:?]
         at org.onosproject.odtn.impl.GnpyManager.setPathPower(GnpyManager.java:509) ~[?:?]
         at org.onosproject.odtn.impl.GnpyManager$InternalIntentListener.event(GnpyManager.java:493) ~[?:?]
         at org.onosproject.odtn.impl.GnpyManager$InternalIntentListener.event(GnpyManager.java:484) ~[?:?]
         at org.onosproject.event.ListenerRegistry.process(ListenerRegistry.java:66) [186:org.onosproject.onos-api:2.3.1.SNAPSHOT]
         at org.onosproject.event.impl.CoreEventDispatcher$DispatchLoop.process(CoreEventDispatcher.java:198) [190:org.onosproject.onos-core-net:2.3.1.SNAPSHOT]
         at org.onosproject.event.impl.CoreEventDispatcher$DispatchLoop.run(CoreEventDispatcher.java:180) [190:org.onosproject.onos-core-net:2.3.1.SNAPSHOT]
         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
         at java.lang.Thread.run(Thread.java:834) [?:?]
 Caused by: org.onosproject.netconf.NetconfException: Failed to edit configuration.
         ... 13 more
 Caused by: org.onosproject.netconf.NetconfException: Interrupted waiting for reply for request
 #440
 <?xml version="1.0" encoding="UTF-8"?><rpc message-id="20"  xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
 <edit-config>
 <target><running/></target>
 <default-operation>merge</default-operation>
 <config xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
 <media-channels xmlns="http://czechlight.cesnet.cz/yang/czechlight-roadm-device"><channel>16.5</channel><drop><power>-5.0</power></drop></media-channels></config>
 </edit-config>
 </rpc>
 ##

         at org.onosproject.netconf.ctl.impl.NetconfSessionMinaImpl.sendRequest(NetconfSessionMinaImpl.java:666) ~[?:?]
         at org.onosproject.netconf.ctl.impl.NetconfSessionMinaImpl.sendRequest(NetconfSessionMinaImpl.java:644) ~[?:?]
         at org.onosproject.netconf.ctl.impl.NetconfSessionMinaImpl.requestSync(NetconfSessionMinaImpl.java:514) ~[?:?]
         at org.onosproject.netconf.ctl.impl.NetconfSessionMinaImpl.requestSync(NetconfSessionMinaImpl.java:509) ~[?:?]
         at org.onosproject.netconf.AbstractNetconfSession.editConfig(AbstractNetconfSession.java:251) ~[?:?]
         at org.onosproject.drivers.czechlight.CzechLightPowerConfig.doEditConfig(CzechLightPowerConfig.java:276) ~[?:?]
         ... 12 more
 Caused by: java.lang.InterruptedException
         at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:385) ~[?:?]
         at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022) ~[?:?]
         at org.onosproject.netconf.ctl.impl.NetconfSessionMinaImpl.sendRequest(NetconfSessionMinaImpl.java:662) ~[?:?]
         at org.onosproject.netconf.ctl.impl.NetconfSessionMinaImpl.sendRequest(NetconfSessionMinaImpl.java:644) ~[?:?]
         at org.onosproject.netconf.ctl.impl.NetconfSessionMinaImpl.requestSync(NetconfSessionMinaImpl.java:514) ~[?:?]
         at org.onosproject.netconf.ctl.impl.NetconfSessionMinaImpl.requestSync(NetconfSessionMinaImpl.java:509) ~[?:?]
         at org.onosproject.netconf.AbstractNetconfSession.editConfig(AbstractNetconfSession.java:251) ~[?:?]
         at org.onosproject.drivers.czechlight.CzechLightPowerConfig.doEditConfig(CzechLightPowerConfig.java:276) ~[?:?]
         ... 12 more
 2020-02-23T16:33:05,197 | WARN  | onos-event-dispatch-programming0 | CoreEventDispatcher              | 190 - org.onosproject.onos-core-net - 2.3.1.SNAPSHOT | Dispatch loop interrupted

I solved this via a deferred executor running on a static thread pool.
This was inspired by org.onosproject.restconf.restconfmanager (which,
BTW, I think instantiates an ExecutorService, but then happily executes
tasks on a default one; I think that a reviewer should take a look at
that).

Change-Id: I8f214f634a162c68e90bffc10d9c62bbbdfad26b